-- noinspection SqlNoDataSourceInspectionForFile
SET MODE Oracle;

CREATE TABLE EXAMPLE_ENTITY (
  ID NUMBER(5) PRIMARY KEY,
  VALUE        VARCHAR(255)
);

CREATE SEQUENCE SEQ_ID INCREMENT BY 1 NOCYCLE;

INSERT INTO EXAMPLE_ENTITY(ID, VALUE) VALUES (SEQ_ID.nextval, 'value1');
INSERT INTO EXAMPLE_ENTITY(ID, VALUE) VALUES (SEQ_ID.nextval, 'value2');
INSERT INTO EXAMPLE_ENTITY(ID, VALUE) VALUES (SEQ_ID.nextval, 'value3');
INSERT INTO EXAMPLE_ENTITY(ID, VALUE) VALUES (SEQ_ID.nextval, 'value4');